# config.yaml
# Input and output directories
input_dir: 'data/input'
output_dir: 'data/output'

# Model configuration
# model_path: "../VIT-Base-model"
model_path: './ViT-Base-model'

# File validation settings
allowed_extensions:
  - jpg
  - jpeg
  - png
  - bmp
max_file_size_mb: 10 # Maximum file size in MB

# Server settings
host: '0.0.0.0'
port: 8000

# API settings
api_version: 'v1'
